#!/bin/bash

echo 'X or Wayland? (x/w)'
read choice

if [ "$choice" = "x" ]; then
    curl https://raw.githubusercontent.com/spocksbeerd/dotfiles/main/.local/bin/configure/configure.sh > $HOME/installxsystem.sh
else
    curl https://raw.githubusercontent.com/spocksbeerd/dotfiles-wayland/main/.local/bin/configure/configure.sh > $HOME/installwaylandsystem.sh

chmod +x $HOME/install*
$HOME/install*
