#!/bin/bash

echo 'X or Wayland? (x/w)'
read -e choice

if [ "$choice" = "x" ]; then
    source <(curl -s https://raw.githubusercontent.com/spocksbeerd/dotfiles/main/.local/bin/configure/configure.sh)
else
    source <(curl -s https://raw.githubusercontent.com/spocksbeerd/dotfiles-wayland/main/.local/bin/configure/configure.sh)
fi
